version: '3'
services:
  postgres-db:
    image: postgres:alpine
    container_name: qr_reader_database_local
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: localPostgres
      POSTGRES_PASSWORD: localPassword